# Generated by Django 5.2.14 on 2026-05-15 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceUser',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=256)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('restaurant_count', models.PositiveIntegerField(default=1)),
                ('date_of_birth', models.CharField(blank=True, max_length=32)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('can_manage_users', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=64, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('plan_name', models.CharField(blank=True, max_length=64)),
                ('trial_start', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='aud', max_length=8)),
                ('interval', models.CharField(default='month', max_length=16)),
                ('is_primary', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.workspaceuser')),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=64, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(db_index=True, max_length=32)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='aud', max_length=8)),
                ('hosted_invoice_url', models.URLField(blank=True, max_length=512)),
                ('invoice_pdf', models.URLField(blank=True, max_length=512)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.workspaceuser')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
    ]
