# Generated by Django 5.2.14 on 2026-05-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceuser',
            name='reset_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspaceuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
