# Generated by Django 5.2.14 on 2026-05-27 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workspaceuser_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Chat', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='accounts.workspaceuser')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=16)),
                ('content', models.TextField(blank=True)),
                ('timestamp', models.BigIntegerField()),
                ('agent', models.CharField(blank=True, max_length=64)),
                ('files', models.JSONField(blank=True, default=list)),
                ('agent_result', models.JSONField(blank=True, null=True)),
                ('process_state', models.JSONField(blank=True, null=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.chatsession')),
            ],
            options={
                'ordering': ['ordering', 'timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='accounts_cs_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'ordering'], name='accounts_cm_session_ord_idx'),
        ),
    ]
