# Generated by Django 5.2.14 on 2026-05-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceuser',
            name='password_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
