# Generated by Django 5.2.14 on 2026-06-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_password_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='management_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='subscription',
            name='management_url_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
