# Generated by Django 5.2.14 on 2026-06-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subscription_management_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspaceuser',
            name='date_of_birth',
        ),
    ]
